# See docker-compile file versions here: https://docs.docker.com/compose/compose-file/
version: "3.8"
services: # Containers
  frontend: # Give it whatever name you want
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - MY_ENV=TIM
